import assert from 'node:assert/strict'

export async function runLotteryFlow(page) {
  const state = () => page.evaluate(() => JSON.parse(localStorage.getItem('who-is-raising:session:v1')))
  const enter = async () => { await page.getByRole('button', { name: '进入私密操作' }).click(); await page.getByText('你的回合', { exact: true }).waitFor(); while (await page.getByRole('button', { name: '知道了', exact: true }).count()) await page.getByRole('button', { name: '知道了', exact: true }).last().click() }
  const submit = async () => { if (await page.getByRole('button', { name: '关闭彩票', exact: true }).isVisible()) await page.getByRole('button', { name: '关闭彩票', exact: true }).click(); await page.getByRole('button', { name: '确认提交', exact: true }).click(); await page.getByRole('button', { name: '确定提交', exact: true }).click() }
  await page.goto('http://127.0.0.1:5181')
  await page.evaluate(async () => {
    const { createSession, createDefaultSettings } = await import('/src/game/session.ts')
    const settings = createDefaultSettings(3)
    settings.rounds = 2; settings.animationSpeed = 'reduced'; settings.systemAuctionCardsPerRound = 0; settings.cardGrantProbability = 0; settings.identitySettings.enabled = false
    const s = createSession(['彩甲', '彩乙', '彩丙'], settings)
    s.phase = 'handoff'; s.players[2].balanceUnits = 0
    s.roundStartBalanceUnits = Object.fromEntries(s.players.map(p => [p.id, p.balanceUnits]))
    localStorage.setItem('who-is-raising:session:v1', JSON.stringify(s))
  })
  await page.reload(); await page.getByRole('button', { name: /继续第/ }).click(); await enter()
  const panel = page.getByTestId('lottery-panel')
  await page.getByTestId('lottery-entry').click()
  const range = page.getByLabel('秘密下注', { exact: true })
  const setBid = async value => range.evaluate((input, next) => {
    Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(input, String(next))
    input.dispatchEvent(new Event('input', { bubbles: true })); input.dispatchEvent(new Event('change', { bubbles: true }))
  }, value)
  await page.getByRole('button', { name: '关闭彩票', exact: true }).click()
  await setBid(60)
  await page.getByTestId('lottery-entry').click()
  assert.equal(await panel.getByRole('button', { name: /确认购票/ }).isDisabled(), true)
  assert.ok((await panel.textContent()).includes('请先减少 1.5 金币'))
  await page.getByRole('button', { name: '关闭彩票', exact: true }).click()
  await setBid(0)
  await page.getByTestId('lottery-entry').click()
  assert.equal(await page.locator('#root').evaluate(root => root.inert), true)
  await page.keyboard.press('Escape')
  assert.equal(await panel.count(), 0)
  await page.getByTestId('lottery-entry').click()
  await panel.getByRole('button', { name: '1 号', exact: true }).click()
  await panel.getByRole('button', { name: '2 号', exact: true }).click()
  assert.equal(await panel.getByRole('button', { name: '2 号', exact: true }).getAttribute('aria-pressed'), 'true')
  await panel.getByRole('button', { name: '1 号', exact: true }).click()
  await panel.getByRole('button', { name: /确认购票/ }).click()
  const bought = await state()
  assert.equal(bought.players[0].balanceUnits, 57)
  assert.equal(bought.lottery.poolUnits, 7)
  assert.equal(bought.lottery.openingPoolUnits, 3)
  await page.reload(); await page.getByRole('button', { name: /继续第/ }).click(); await enter()
  await page.getByTestId('lottery-entry').click()
  assert.deepEqual((await state()).lottery, bought.lottery)
  assert.equal(await panel.getByRole('button', { name: /确认购票/ }).count(), 1)
  await submit(); await enter(); await page.getByTestId('lottery-entry').click()
  assert.equal(await panel.getByRole('button', { name: '1 号 已被选', exact: true }).isDisabled(), true)
  assert.equal((await panel.textContent()).includes('彩甲'), false)
  await panel.getByRole('button', { name: '2 号', exact: true }).click(); await panel.getByRole('button', { name: /确认购票/ }).click()
  await submit(); await enter(); await page.getByTestId('lottery-entry').click()
  assert.ok((await panel.textContent()).includes('你支付 0 金币'))
  await panel.getByRole('button', { name: '3 号', exact: true }).click(); await panel.getByRole('button', { name: /确认购票/ }).click()
  for (const size of [{ width: 360, height: 640 }, { width: 844, height: 390 }, { width: 768, height: 1024 }, { width: 1366, height: 768 }]) {
    await page.setViewportSize(size)
    await panel.scrollIntoViewIfNeeded()
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
    await page.screenshot({ path: `.artifacts/lottery-purchase-${size.width}.png` })
  }
  await page.setViewportSize({ width: 360, height: 640 })
  await page.getByRole('button', { name: '关闭彩票', exact: true }).click()
  const entry = page.getByTestId('lottery-entry')
  assert.ok((await entry.boundingBox()).height <= 64, '主操作页彩票入口应只有一行')
  await entry.scrollIntoViewIfNeeded()
  await page.screenshot({ path: '.artifacts/lottery-entry-360.png' })
  await submit()
  await page.evaluate(() => { Math.random = () => .999 })
  await page.getByRole('button', { name: '揭晓本轮结果' }).click()
  const dialog = page.getByRole('dialog', { name: '幸运开奖', exact: true })
  await dialog.waitFor()
  const first = await state()
  assert.equal(first.results[0].lottery.number, 6)
  assert.equal(first.results[0].lottery.winnerId, null)
  assert.equal(first.lottery.poolUnits, 15)
  assert.equal(await page.locator('#root').evaluate(root => root.inert), true)
  await page.screenshot({ path: '.artifacts/lottery-rollover-360.png' })
  await page.reload(); await page.getByRole('button', { name: /继续第/ }).click(); await dialog.waitFor()
  assert.deepEqual((await state()).results[0].lottery, first.results[0].lottery)
  await dialog.getByRole('button', { name: '收起开奖结果' }).click()
  await page.getByRole('button', { name: '进入下一轮' }).click()
  await page.getByRole('button', { name: '启动抽奖机' }).click()
  await page.getByRole('button', { name: '开始传递' }).click()
  for (let i = 0; i < 3; i++) {
    await enter(); await page.getByTestId('lottery-entry').click()
    assert.ok((await panel.textContent()).includes('末轮'))
    assert.ok((await panel.textContent()).includes('轮初彩票奖池 7.5'))
    if (i === 2) { await panel.getByRole('button', { name: '6 号', exact: true }).click(); await panel.getByRole('button', { name: /确认购票/ }).click() }
    await submit()
  }
  await page.evaluate(() => { Math.random = () => .999 })
  await page.getByRole('button', { name: '揭晓本轮结果' }).click(); await dialog.waitFor()
  const final = await state()
  assert.equal(final.results[1].lottery.number, 6)
  assert.equal(final.results[1].lottery.winnerId, final.players[0].id)
  assert.equal(final.results[1].lottery.prizeUnits, 19)
  assert.equal(final.lottery.poolUnits, 0)
  assert.equal(final.lottery.tickets.length, 0)
  assert.equal(final.results[1].balancesAfter[final.players[0].id], final.players[0].balanceUnits)
  await dialog.getByRole('button', { name: '收起开奖结果' }).click()
  await page.getByRole('button', { name: /查看最终排行榜/ }).click()
  await page.getByText('全局结束', { exact: true }).waitFor()
  assert.equal((await state()).phase, 'finalResult')
  await page.evaluate(async () => {
    const { createSession, createDefaultSettings } = await import('/src/game/session.ts')
    const settings = createDefaultSettings(3); settings.identitySettings.enabled = false; settings.systemAuctionCardsPerRound = 0
    const s = createSession(['双票甲','双票乙','双票丙'], settings); s.phase = 'handoff'
    localStorage.setItem('who-is-raising:session:v1', JSON.stringify(s))
  })
  await page.reload(); await page.getByRole('button', { name: /继续第/ }).click(); await enter()
  await page.getByTestId('lottery-entry').click()
  for (const number of [1,2]) {
    await panel.getByRole('button', { name: `${number} 号`, exact: true }).click()
    await panel.getByRole('button', { name: /确认购票/ }).click()
    const tile = panel.getByRole('button', { name: `${number} 号 已持有`, exact: true })
    assert.equal(await tile.getAttribute('class'), 'is-purchased-now')
    assert.equal(await tile.locator('small').textContent(), '本轮购入')
  }
  assert.equal((await state()).players[0].balanceUnits,54)
  assert.equal((await state()).lottery.poolUnits,11)
  assert.equal(await panel.getByRole('button', { name: /确认购票/ }).count(),0)
  await page.setViewportSize({ width:360,height:740 })
  await page.screenshot({path:'.artifacts/lottery-two-tickets.png'})
  await page.reload(); await page.getByRole('button', { name: /继续第/ }).click(); await enter()
  await page.getByTestId('lottery-entry').click()
  assert.equal(await panel.getByRole('button', { name: /确认购票/ }).count(),0)
  console.log('彩票真人两轮：预算、免费票、独占、改号、刷新、滚存、末轮奖金及四种尺寸通过。')
}
